FROM moul/go-dl-extract
MAINTAINER Manfred Touron <m@42.am> (@moul)
# by inheriting the moul/go-dl-extract, the first RUN means a remote ADD
RUN --md5=cd5567f945366fd4bda65700d139fbbd http://download.opensuse.org/ports/armv7hl/distribution/13.2/appliances/openSUSE-13.2-ARM-JeOS.armv7-rootfs.armv7l-1.12.1-Build32.1.tbz
CMD ["/bin/bash"]

